# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

compute_density <- function(distances, radius) {
    .Call(`_cydar_compute_density`, distances, radius)
}

count_cells <- function(assignments, sample_id, nsamples) {
    .Call(`_cydar_count_cells`, assignments, sample_id, nsamples)
}

drop_redundant <- function(intensities, ordering, assignments, threshold) {
    .Call(`_cydar_drop_redundant`, intensities, ordering, assignments, threshold)
}

median_int_by_sample <- function(exprs, assignments, sample_id, nsamples) {
    .Call(`_cydar_median_int_by_sample`, exprs, assignments, sample_id, nsamples)
}

weighted_median_int <- function(exprs, assignments, sample_id, sample_weight) {
    .Call(`_cydar_weighted_median_int`, exprs, assignments, sample_id, sample_weight)
}

